### ISSUE TITLE
null email and password to firebase (production worked)

### ISSUE THREAD

**Issue by joyoyoyoyoyo** [UCSB-CS189-2016-17-Aerospace/Aerocube-WebApp#1]
It appears that our firebase login was unable to login during tests. I had to reconfigure the event to reference `this.props.handleSubmit`, rather than `this.handleSubmit`.

For some odd reason, during production we can still accessibly use this event and perform the submission, but tests required the change from:
```javascript
 <Button className={styles.blockButton} type="submit" onClick={this.handleSubmit}>
```
to
```javascript
<Button className={styles.blockButton} type="submit" onClick={this.props.handleSubmit}>
```

How is it that our production code can still execute this function and successfully login, but our tests were unable to login until I made the change?

The line that fails is referenced below

```javascript
handleSubmit = (evt) => {
    if(evt && evt.preventDefault) {
      evt.preventDefault();
    } // undefined email and password at this point. (when using this.handleSubmit)
    let userPromise = firebaseService.loginUser(this.props.email, this.props.password); // FAILED LINE 
    userPromise.then((user) => {
```

> [Firebase login entry point code-line](https://github.com/UCSB-CS189-2016-17-Aerospace/Aerocube-WebApp/blob/9df5a768e0f6b6a94046663e034d663e1c9f3c58/app/containers/LoginPage/index.js#L29)

**Comment by elswenson** [comment]
No longer relevant, switched testing frameworks.
